'''
conditional statements
if else , elif 
'''

# keyword (condition) :
#       //body

'''
if else elif
'''
# if condition
# elif condition
# else

# if 50==50:

'''
check whether the name and the reverse of name is equal 
'''

name =input("Enter your name : ")

if name == name [::-1]:
    print("Equal")
else:
    print('Not Equal')

name,salary, char=input("Enter the name and salary of employee ").split(" ")
salary=int(salary)

if name[0] == char:
    salary50=((salary/100)*50)+salary
    print(f"The Employee whose name start with {char} has an increment in salary of 50%\nBefore Increment {salary}\nAfter increment {salary50}")

elif name[0] != char:
    print("Salary not increase , employee did not meet the criteria")

else:
    print("Error")

import random
computer_points=0
my_points=0

# for attempt in range(1,11):
    computer_choice=random.randint(1,5)
    my_choice=int(input("Guess the number which is generated by computer : \n"))
     
    print(f"attempt : {attempt}")
    print(f"Remaining Attempts:{10-attempt}")
    if computer_choice == my_choice:
        print(f"Right Guess : In attempt {attempt } Computer Choice: {computer_choice} My choice: {my_choice}")
        my_points+=1
    else:
       print(f"wrong guess Guess : In attempt {attempt } Computer Choice: {computer_choice} My choice: {my_choice}")
       computer_points+=1

if my_points>computer_points:
    print("Human Win")
elif my_points<computer_points:
    print("Computer Win")
else:
    print("Draw")

from tkinter import *
from tkinter import ttk
import random

class Main:
    def __init__(self,root):
        self.root=root
        self.root.title("Game")
        self.root.geometry("600x600+100+100")

        self.frame=Frame(self.root,bg="cyan")
        self.frame.pack(fill=BOTH,expand=True)

        self.label=Label(self.frame,text="TIC TAC TOE" ,font=("times new roman",30,'bold'),bg="cyan")
        self.label.place(x=160,y=20)

        self.label=Label(self.frame,text="Guess the number",bg="cyan",font=("times new roman",25,'bold'))
        self.label.place(x=160,y=160)
        
        self.my_choice=IntVar()
        self.entr=Entry(self.frame,textvariable=self.my_choice)
        self.entr.place(x=160,y=220,width=300,height=50)

        self.btn=Button(self.frame,text="Guess",bg="Red",fg="black",command=self.guess)
        self.btn.place(x=160,y=320,width=100,height=50)

    def guess(self):
       computer_choice=random.randint(1,5)
       my_choice=self.my_choice.get()
     
    
       if computer_choice == my_choice:
           var="Right Guess"
           self.la=Label(self.frame,text=var,font=("times new roman",40,'bold'),bg="cyan")
           self.la.place(x=160,y=400)
       elif computer_choice !=my_choice:
           var="Wrong Guess"
           self.la=Label(self.frame,text=var,font=("times new roman",40,'bold'),bg="cyan")
           self.la.place(x=160,y=400)
           
 

if __name__ == "__main__":
    root=Tk()
    obj=Main(root)
    root.mainloop()
